project:
  type: website
  output-dir: _site

website:
  title: "ARBO-WATCH"
  search: true
  navbar:
    logo: assets/logo/arbowatch.png
    left:
      - href: index.qmd
        text: Home
      - text: Workshops
        menu:
          - href: workshops/workshop-01/index.qmd
            text: "Module I - Data Collection and Management"
          - href: workshops/workshop-02/index.qmd
            text: "Module II - Introduction to R for Public Health Surveillance"
    right:
      - href: license.qmd
        text: License
      - icon: github
        href: https://github.com/your-org/arbowatch-workshops
        aria-label: GitHub

  sidebar:
    - id: workshop-01
      title: "Module I - Data Collection and Management"
      style: docked
      collapse-level: 2
      contents:
        - text: "Overview"
          href: workshops/workshop-01/index.qmd
        - section: "Days"
          contents:
            - text: "Day 1 — Data Collection and Ethics"
              href: workshops/workshop-01/day-01.qmd
            - text: "Day 2 — Digital Data Collection Tools: Getting Started"
              href: workshops/workshop-01/day-02.qmd
            - text: "Day 3 — KoboToolbox: Getting Hands-On"
              href: workshops/workshop-01/day-03.qmd
            - text: "Day 4 — KoboToolbox: Advanced"
              href: workshops/workshop-01/day-04.qmd
            - text: "Day 5 — Fundamentals of Excel"
              href: workshops/workshop-01/day-05.qmd
            - text: "Day 6 — Fundamentals of Excel"
              href: workshops/workshop-01/day-06.qmd

    - id: workshop-02
      title: "Module II - Introduction to R for Public Health Surveillance"
      style: docked
      collapse-level: 2
      contents:
        - text: "Overview"
          href: workshops/workshop-02/index.qmd
        - section: "Days"
          contents:
            - text: "Day 1 — 01 Jun 2024"
              href: workshops/workshop-02/day-01.qmd
            - text: "Day 2 — 02 Jun 2024"
              href: workshops/workshop-02/day-02.qmd


format:
  html:
    css: styles.css
    toc: true
    toc-depth: 2
    code-tools: false
    code-copy: false
  revealjs:
    theme: default
    slide-number: true
    chalkboard: false
    preview-links: true